const { supabase } = require('../config');
const { validateWalletAddress } = require('../middleware/verifyAdmin');
const { createNotification } = require('../services/notificationService');

const getRetentionPolicies = async (req, res) => {
  try {
    const { data: policies, error } = await supabase
      .from('retention_policies')
      .select('*')
      .eq('is_active', true)
      .order('created_at', { ascending: false });
    if (error) throw error;
    res.json({ success: true, policies });
  } catch (error) {
    console.error('Get retention policies error:', error);
    res.status(500).json({ error: 'Failed to get retention policies' });
  }
};

const createRetentionPolicy = async (req, res) => {
  try {
    const { name, caseType, retentionDays, archiveMethod, jurisdiction, lawReference, userWallet } =
      req.body;
    if (!validateWalletAddress(userWallet)) {
      return res.status(400).json({ error: 'Invalid wallet address' });
    }
    const { data: policy, error } = await supabase
      .from('retention_policies')
      .insert({
        name,
        case_type: caseType,
        retention_days: retentionDays,
        archive_method: archiveMethod,
        jurisdiction,
        law_reference: lawReference,
        created_by: userWallet,
      })
      .select()
      .single();
    if (error) throw error;
    res.json({ success: true, policy });
  } catch (error) {
    console.error('Create retention policy error:', error);
    res.status(500).json({ error: 'Failed to create retention policy' });
  }
};

const exportTimelinePdf = async (req, res) => {
  try {
    const { caseId, evidence } = req.body;

    if (!Array.isArray(evidence) || evidence.length === 0) {
      return res.status(400).json({ error: 'Evidence must be a non-empty array.' });
    }

    const pdfContent = `CASE EVIDENCE TIMELINE REPORT\nCase ID: ${caseId}\nGenerated: ${new Date().toLocaleString()}\nTotal Evidence Items: ${evidence.length}\n\nEVIDENCE CHRONOLOGY:\n${evidence.map((item, i) => `${i + 1}. ${item.title}\n   Type: ${item.type}\n   Date: ${new Date(item.timestamp).toLocaleString()}\n   Submitted by: ${(item.submitted_by || 'unknown').substring(0, 8)}...\n   Hash: ${item.hash}\n`).join('')}\nGenerated by EVID-DGC Blockchain Evidence Management System.`;
    res.setHeader('Content-Type', 'text/plain');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="timeline_${caseId}_${new Date().toISOString().split('T')[0]}.txt"`,
    );
    res.send(Buffer.from(pdfContent));
  } catch (error) {
    console.error('Timeline PDF export error:', error);
    res.status(500).json({ error: 'Failed to export timeline as PDF' });
  }
};

// Get evidence with expiry information
const getEvidenceExpiry = async (req, res) => {
  try {
    const { filter = 'all' } = req.query;
    let query = supabase.from('evidence').select('*');

    const now = new Date();
    const thirtyDaysFromNow = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    const sevenDaysFromNow = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

    switch (filter) {
      case 'expired':
        query = query.lt('expiry_date', now.toISOString()).eq('legal_hold', false);
        break;
      case '30days':
        query = query
          .lte('expiry_date', thirtyDaysFromNow.toISOString())
          .gte('expiry_date', now.toISOString());
        break;
      case '7days':
        query = query
          .lte('expiry_date', sevenDaysFromNow.toISOString())
          .gte('expiry_date', now.toISOString());
        break;
      case 'legal_hold':
        query = query.eq('legal_hold', true);
        break;
    }

    const { data: evidence, error } = await query.order('expiry_date', { ascending: true });
    if (error) throw error;

    res.json({ success: true, evidence });
  } catch (error) {
    console.error('Get evidence expiry error:', error);
    res.status(500).json({ error: 'Failed to get evidence expiry information' });
  }
};

// Set legal hold on evidence
const setLegalHold = async (req, res) => {
  try {
    const { id } = req.params;
    const { legalHold, userWallet } = req.body;

    if (!validateWalletAddress(userWallet)) {
      return res.status(400).json({ error: 'Invalid wallet address' });
    }

    const { error } = await supabase
      .from('evidence')
      .update({ legal_hold: legalHold })
      .eq('id', id);

    if (error) throw error;

    await supabase.from('activity_logs').insert({
      user_id: userWallet,
      action: legalHold ? 'legal_hold_set' : 'legal_hold_removed',
      details: `Evidence ID: ${id}`,
      timestamp: new Date().toISOString(),
    });

    res.json({ success: true });
  } catch (error) {
    console.error('Set legal hold error:', error);
    res.status(500).json({ error: 'Failed to set legal hold' });
  }
};

// Apply retention policy to multiple evidence
const bulkRetentionPolicy = async (req, res) => {
  try {
    const { policyId, evidenceIds, userWallet } = req.body;

    if (!validateWalletAddress(userWallet)) {
      return res.status(400).json({ error: 'Invalid wallet address' });
    }

    const { data: policy, error: policyError } = await supabase
      .from('retention_policies')
      .select('*')
      .eq('id', policyId)
      .single();

    if (policyError || !policy) {
      return res.status(404).json({ error: 'Retention policy not found' });
    }

    const expiryDate = new Date();
    expiryDate.setDate(expiryDate.getDate() + policy.retention_days);

    const { error } = await supabase
      .from('evidence')
      .update({
        retention_policy_id: policyId,
        expiry_date: expiryDate.toISOString(),
      })
      .in('id', evidenceIds);

    if (error) throw error;

    res.json({ success: true, updated: evidenceIds.length });
  } catch (error) {
    console.error('Bulk retention policy error:', error);
    res.status(500).json({ error: 'Failed to apply retention policy' });
  }
};

// Check for expiring evidence and send notifications
const checkExpiry = async (req, res) => {
  try {
    const now = new Date();
    const thirtyDaysFromNow = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);

    let notificationsSent = 0;

    const { data: expiring30, error: error30 } = await supabase
      .from('evidence')
      .select('*')
      .lte('expiry_date', thirtyDaysFromNow.toISOString())
      .gte('expiry_date', now.toISOString())
      .eq('legal_hold', false);

    if (expiring30) {
      for (const evidence of expiring30) {
        await createNotification(
          evidence.submitted_by,
          'Evidence Expiry Warning',
          `Evidence "${evidence.title}" will expire in 30 days`,
          'system',
          { evidence_id: evidence.id, expiry_date: evidence.expiry_date },
        );
        notificationsSent++;
      }
    }

    res.json({ success: true, notifications_sent: notificationsSent });
  } catch (error) {
    console.error('Check expiry error:', error);
    res.status(500).json({ error: 'Failed to check expiring evidence' });
  }
};

module.exports = {
  getRetentionPolicies,
  createRetentionPolicy,
  exportTimelinePdf,
  getEvidenceExpiry,
  setLegalHold,
  bulkRetentionPolicy,
  checkExpiry,
};
